### ISSUE TITLE
Docker Compose Boot Order Fix

### ISSUE THREAD

**Issue by reustonium** [reustonium/uptime-sentry#6]
Ensure that the Server starts before the Client.

**Comment by PeterSulcs** [comment]
I would try adding depends_on, i.e:
```

version: "2"

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
     - "443:443"
    depends_on:
      - dashboards
      - gitlab
      - hub
      - bokeh
```
